"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
require("express-async-errors");
var express_1 = __importDefault(require("express"));
var error_1 = __importDefault(require("./middlewares/error"));
var authRouter_1 = __importDefault(require("./routes/authRouter"));
var orderRouter_1 = __importDefault(require("./routes/orderRouter"));
var productRouter_1 = __importDefault(require("./routes/productRouter"));
var userRouter_1 = __importDefault(require("./routes/userRouter"));
var app = (0, express_1.default)();
app.use(express_1.default.json());
app.use('/login', authRouter_1.default);
app.use('/products', productRouter_1.default);
app.use('/users', userRouter_1.default);
app.use('/orders', orderRouter_1.default);
app.use(error_1.default);
exports.default = app;
